<?php

namespace Tests\Fhp\Protocol;

use Fhp\Protocol\DialogInitialization;

class DialogInitializationTest extends \PHPUnit\Framework\TestCase
{
    // Tests that objects serialized with this same version of the library can be deserialized again.
    public function testSerializableInterfaceMigration()
    {
        $kundensystemId = 'kunden-system-id';
        $needTanForSegment = 'test-segment';

        $object = new DialogInitializationTestModel(
            $kundensystemId,
            $needTanForSegment,
        );

        $string = serialize($object);

        /** @var DialogInitialization $object2 */
        $object2 = unserialize($string);
        self::assertIsObject($object2);
        self::assertNotSame($object, $object2);
        unset($object);

        // Test child class: DialogInitialization
        self::assertEquals($object2->getKundensystemId(), $kundensystemId);

        // test parent class: BaseClass
        self::assertEquals($object2->getNeedTanForSegment(), $needTanForSegment);
    }

    // Tests that objects serialized with the oldest version of the library to which we still need to keep backward
    // compatibility can still be deserialized. Notably, we have dropped support for the format of the \Serializable
    // interface, which started with "C:...". The new "O:..." format has been produced since php-fints version 3.3 if
    // combined with PHP version 7.4 or higher (which was required since php-fints version 3.4).
    public function testSerializableInterfaceMigrationFromString()
    {
        $kundensystemId = 'kunden-system-id2';
        $needTanForSegment = 'test-segment2';

        // This is the output generated by serialize($object)` in the test case above.
        $string = 'O:48:"Tests\Fhp\Protocol\DialogInitializationTestModel":5:{i:0;a:3:{i:0;N;i:1;N;i:2;s:13:"test-segment2";}i:1;N;i:2;s:17:"kunden-system-id2";i:3;N;i:4;N;}';

        /** @var DialogInitialization $object2 */
        $object2 = unserialize($string);
        self::assertIsObject($object2);

        // Test child class: DialogInitialization
        self::assertEquals($object2->getKundensystemId(), $kundensystemId);

        // test parent class: BaseClass
        self::assertEquals($object2->getNeedTanForSegment(), $needTanForSegment);
    }
}
